# Generated by Django 5.1.7 on 2025-03-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('releasedYear', models.CharField(max_length=10)),
                ('processorName', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
